language: python

python:
  - "2.7"
  - "3.5"
install:
  - pip install -e .
  - pip install coveralls # For coveralls.io specifically
  - pip install -r tests_requirements.txt
script:
  # Main tests, w/ coverage!
  - inv test --coverage
after_success:
- coveralls
